"""chatbot_basic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RyCKGJ9fHkM5UUhi-S2002O3_J2s6F4-
"""

import nltk
import string
from nltk.tokenize import sent_tokenize
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from google.colab import files

# Download NLTK resources
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')

uploaded = files.upload()

sentences = []
word_tokens = []

for filename in uploaded.keys():
    print(f"Uploaded file: {filename}")
    with open(filename, 'r', errors='ignore') as file:
        raw = file.read().lower()
        sentences += sent_tokenize(raw)
        word_tokens += nltk.word_tokenize(raw)


lemmer = nltk.stem.WordNetLemmatizer()
def LemNormalize(text):
    tokens = nltk.word_tokenize(text.lower().translate(dict((ord(punct), None) for punct in string.punctuation)))
    return [lemmer.lemmatize(token) for token in tokens]


TfidfVec = TfidfVectorizer(stop_words='english')
tfidf_matrix = TfidfVec.fit_transform(sentences)

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

def response(user_response):
    robo_response = ''
    user_response = user_response.lower()
    sentences.append(user_response)
    tfidf_matrix_new = TfidfVec.fit_transform(sentences)
    vals = cosine_similarity(tfidf_matrix_new[-1], tfidf_matrix_new)
    idx = vals.argsort()[0][-2]
    flat = vals.flatten()
    flat.sort()
    req_tfidf = flat[-2]
    if(req_tfidf == 0):
        robo_response += " I am sorry, unable to understand you"
    else:
        robo_response += sentences[idx]
    sentences.remove(user_response)
    return robo_response

flag = True
print("Bot : Hello, this is a very basic retrieval Chatbot. Enter 'Hi' to start and 'Bye' to end")
while(flag):
    user = input("User : ")
    if(user.lower() == "bye"):
        print("Bot : nice talking to you. tata!!")
        flag = False
    else:
        if(user.lower() == "thank you" or user.lower() == "thanks"):
            print("Bot : You are welcome")
        else:
            if(user.lower() == "hi"):
                print("Bot : Hello! How can I help you?")
            else:
                print("Bot : ", end="")
                print(response(user))







